
version: 2

models:
  - name: dummy_table
    description: "A dummy model for testing purposes"
    columns:
      - name: dummy_id
        description: "The unique identifier for each record"
        tests:
          - not_null
          - unique
sources:
  - name: cgm_abbot_connector
    database: cgm_abbot_connector
    tables:
      - name: glucose_register

semantic_models:
   - name: glucose_register
     model: ref('glucose_register')

